name: Service Deployment


on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
  

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout closed
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin docker.io

    - name: Set Docker BuildKit
      run: export DOCKER_BUILDKIT=1

    - name: Build Docker Image
      run: |
        docker build \
            --build-arg PRODUCTION=${{ secrets.PRODUCTION }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_URL=${{ secrets.DB_URL }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -t ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} \
            .  
        docker push ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
